version: "3.8"
services:
  rabbitmq:
    image: 'rabbitmq:4.0.7-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s  
    networks:
      - rabbitmq-network
  springboot-rabbitmq:
    image: 'sachinextgen/springbootrabbitmq:0.0.1'
    container_name: springbootrabbitmq
    ports:
        - '8080:8080'
    networks:
        - rabbitmq-network
    depends_on:
        - rabbitmq

networks:
  rabbitmq-network:   
    driver: bridge









